name: Graphene CI - Publish to PlatformIO registry

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install unity test framework
      run: |
        git clone https://github.com/ThrowTheSwitch/Unity.git
        cd Unity/
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Run unit tests
      run: |
        ./scripts/tests.sh

  publish:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install -U platformio

    - name: Authenticate PlatformIO
      env:
        PIO_USERNAME: ${{ secrets.PIO_USERNAME }}
        PIO_PASSWORD: ${{ secrets.PIO_PASSWORD }}
      run: |
        pio account login -u $PIO_USERNAME -p $PIO_PASSWORD

    - name: Publish Package
      run: |
        ./scripts/publish.sh
