#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only)

echo "*--- staged files ---*"
for FILE in $STAGED_FILES; do
	echo $FILE
done
echo "*--------------------*"

echo "-[pre-commit] Running formatter..."
# Run the formatter
./format.sh
echo "-[pre-commit] Code formatted"

# restage formatted files
for FILE in $STAGED_FILES; do
	git add $FILE
done
